### PR TITLE
Convert vultr-node to typescript (Fixes #393)

### LINKED ISSUE #393: [Feature] Typescript Support
It would be much easier to work with the Library, if typescript-definitions would be available for it.

### PR DESCRIPTION
**Pull request by skooch**
## Description

Converted the codebase to typescript. I've not moved the tests over, but they work.

A reviewer probably should:
* Actually try to interact with the API with the library (I haven't had time yet)
* Look at the strange syntax changes I (fixed?) in `firewall.ts` and make sure they're intended
* Review `types.ts`, `index.ts` and `utils.ts` as this is where the most changes actually are

## Related Issues

#393 

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by AFatalErrror** [comment]
Awesome, thanks! Ill take a look soon.

**Comment by skooch** [comment]
> Awesome, thanks! Ill take a look soon.

How soon?

**Comment by AFatalErrror** [comment]
We appreciate the PR, but we're going to keep this repo as node(js) and create a new typescript repo.  If you want to contribute to that we can follow up with you when that's underway

**Comment by skooch** [comment]
Thanks for the update @AFatalErrror. Do you know when this might be happening? I may just fork if there's no timeline

**Pull request closed without merging**
