### PR TITLE
Fix issue 451

### PR DESCRIPTION
**Pull request by gabos31**

### CODE REVIEW

**Comment by ddymko** [comment]
@gabos31 thanks for the PR, can you remove the `CHANGELOG.md` update? We will submit that in specific release PR.

Also we can not worry about the `codeQL`  failures. I'll look into this

**Comment by ddymko** [comment]
Not sure why the checks aren't updating? Travis had passed https://travis-ci.com/github/vultr/vultr-node/builds/220801147

**Comment by gabos31** [comment]
@ddymko it seems now the checks look good

**Review by spencerkordecki — APPROVED** [review]

**Comment by ddymko** [comment]
relates to #451

**Pull request merged**
